# Site settings
title: Vineethkumar Marpadge ☁️ - Cloud Engineer 2 at AWS | 12x AWS Certified Golden Jacket Holder
email: vineethkumarmarpadge@gmail.com
description: >-
  Cloud Engineer 2 at AWS with 5+ years of experience. 12x AWS Certified Golden Jacket Holder, 1x Terraform Certified.
  Specializing in cloud infrastructure, resolved 200+ complex issues, achieved 40% cost savings.
baseurl: "/vineethkumarmarpadge.github.io" # the subpath of your site
url: "https://vmarpadge.github.io" # the base hostname & protocol for your site
twitter_username: vineethkumar_aws
github_username: vmarpadge
linkedin_username: vmarpadge

# SEO and Social Media
logo: /assets/images/profile.jpg
social:
  name: Vineethkumar Marpadge ☁️
  links:
    - https://linkedin.com/in/vineethkumar-marpadge
    - https://github.com/vineethkumar-marpadge

# Build settings
markdown: kramdown
theme: minima
plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-seo-tag

# Custom variables
author:
  name: Vineethkumar Marpadge ☁️
  title: Cloud Support Engineer 2
  company: Amazon Web Services (AWS)
  location: India
  image: /assets/images/profile.jpg
  bio: >-
    Motivated and customer-focused AWS engineer with 5+ years of experience providing technical support 
    for cloud-based systems. 12x AWS Certified Golden Jacket Holder, 1x Terraform Certified. Successfully resolved 200+ complex 
    cloud infrastructure issues and achieved 40% cost savings through optimized cloud solutions.

# Navigation
header_pages:
  - about.md
  - experience.md
  - skills.md
  - projects.md
  - blog.md
  - contact.md

# Collections
collections:
  case_studies:
    output: true
    permalink: /:collection/:name/

# Exclude from processing
exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
